# Default environments are `development` with hugo server and `production` with hugo.

baseurl = 'https://www.les.cx/'
cleanDestinationDir = true
defaultcontentlanguage = 'en'
#defaultcontentlanguageinsubdir = false
disablehugogeneratorinject = true
disablekinds = ['rss']
enableemoji = false
enablegitinfo = false
#enableinlineshortcodes = false
#enablemissingtranslationplaceholders = false
enablerobotstxt = true
hascjklanguage = false
languagecode = 'en-us'
paginate = 10.0
paginatepath = 'page'
pluralizelisttitles = true
#refLinksErrorLevel = 'ERROR'
#refLinksNotFoundURL
#rssLimit = -1
summarylength = 70.0
theme = ['kafkaesk']
timeout = '30s'
timezone = 'Europe/Berlin'
title = 'Luca Etienne Schulz'
titlecasestyle = 'AP'

[build]
  nojsconfiginassets = true

[security]
  [security.exec]
    allow = ['^go$']

[taxonomies]
    module = 'modules'
    semester = 'semesters'

[mediaTypes]
  [mediaTypes.'application/atom+xml']
    suffixes = ['xml']

[outputFormats]
  [outputFormats.Atom]
    mediaType = 'application/atom+xml'
    baseName = 'index'
    inPlainText = false

[outputs]
  home = ['html', 'Atom']