copyright = 'Except when noted, the contents of this site are licensed under the Creative Commons Attribution 4.0 License, and code is licensed under a BSD license. See https://www.les.cx/copyright for more information'
baseurl = 'https://www.les.cx/'
cleanDestinationDir = true
defaultcontentlanguage = 'en'
#defaultcontentlanguageinsubdir = false
disablehugogeneratorinject = true
disableKinds = ['taxonomy']
enablegitinfo = true
#enableinlineshortcodes = false
#enablemissingtranslationplaceholders = false
languagecode = 'en-us'
timeout = '30s'
timezone = 'Europe/Berlin'
title = 'Luca Etienne Schulz'

[author]
  name = 'Luca Etienne Schulz'
  email = 'luca@les.cx'
  github = 'https://github.com/lescx'
  codeberg = 'https://codeberg.org/les/www.les.cx'
  nostr = 'npub1wnwxt4hg3xg6egc4v8r5zjclf0v2745yq50t5uzhx794h2z8gwwqszpm3w'

[build]
  nojsconfiginassets = true

[security]
  [security.exec]
    allow = ['^go$']

[outputs]
  home = 'HTML'
  taxonomy = ['html']
  term = ['html']
