[[social]]
  name = "nostr"
  url = ""
  weight = 10
[[social]]
  name = "Codeberg"
  url = "https://codeberg.org/les"
  weight = 20
[[social]]
  name = "GitHub"
  url = "https://github.com/lescx"
  weight = 30

[[legal]]
  name = 'copyright'
  url = '/copyright'
  weight = 10
[[legal]]
  name = 'privacy policy'
  url = '/privacy-policy'
  weight = 20
