[[main]]
  name = 'Articles'
  url = '/articles'
  weight = 10
  post = "<a href='/articles/rss.xml'><img src='example.com/rss.jpg'></a>"
[[main]]
  name = 'University'
  url = '/university'
  post = "<a href='/university/rss.xml'><img src='example.com/rss.jpg'></a>"
  weight = 20
[[main]]
  name = 'Contact'
  url = '/contact'
  weight = 30

[[protocol]]
  name = 'HTTPS'
  url = '/'
  weight = 10
[[protocol]]
  name = 'Gemini'
  url = 'gemini://les.cx'
  weight = 20
[[protocol]]
  name = 'Tor'
  url = 'http://placeholderlescx.onion'
  weight = 30

[[legal]]
  name = 'copyright'
  url = '/copyright'
  weight = 10
[[legal]]
  name = 'privacy policy'
  url = '/privacy-policy'
  weight = 20

