[[social]]
  name = "HTTPS"
  url = "https://www.les.cx"
  weight = 99
[[social]]
  name = "nostr"
  url = "npub1wnwxt4hg3xg6egc4v8r5zjclf0v2745yq50t5uzhx794h2z8gwwqszpm3w"
  weight = 10
[[social]]
  name = "Codeberg"
  url = "https://codeberg.org/les"
  weight = 20
[[social]]
  name = "GitHub"
  url = "https://github.com/lescx"
  weight = 30

[[legal]]
  name = 'home'
  url = '/'
  weight = 99
[[legal]]
  name = 'contact'
  url = '/contact'
  weight = 5
[[legal]]
  name = 'copyright'
  url = '/copyright'
  weight = 20
[[legal]]
  name = 'privacy policy'
  url = '/privacy-policy'
  weight = 10
