name = "Kafkaesk"
license = "BSD-3-Clause"
licenselink = "https://codeberg.org/les/www.les.cx/src/branch/main/static/LICENSE"
description = ""
homepage = "https://www.les.cx"
min_version = "0.117.0"

[author]
  name = "Luca Etienne Schulz"
  homepage = "https://www.les.cx"
