name = "Kafkaesk"
license = "BSD-3-Clause"
#licenselink = "https://codeberg.org/les/yourtheme/blob/master/LICENSE"
description = ""
homepage = "https://www.les.cx"
tags = []
features = []
min_version = "0.117.0"

[author]
  name = "Luca Etienne Schulz"
  homepage = "https://www.les.cx"
